import type { Category, Dish, Restaurant } from "@/types";

export const fallbackCategories: Category[] = [
  { id: "bun-pho", name: "Bún phở", slug: "bun-pho", description: "Các món nước dễ ăn cho bữa sáng và trưa." },
  { id: "com", name: "Cơm", slug: "com", description: "No bụng, quen vị, hợp bữa chính." },
  { id: "an-vat", name: "Ăn vặt", slug: "an-vat", description: "Gợi ý nhẹ bụng cho buổi chiều." },
  { id: "lau-nuong", name: "Lẩu nướng", slug: "lau-nuong", description: "Hợp đi nhóm hoặc cuối tuần." },
  { id: "healthy", name: "Healthy", slug: "healthy", description: "Ít dầu mỡ, cân bằng và dễ đặt." },
];

export const fallbackRestaurants: Restaurant[] = [
  { id: "quan-nha", name: "Quán Nhà", slug: "quan-nha", district: "Quận 1", rating: 4.6 },
  { id: "bep-sai-gon", name: "Bếp Sài Gòn", slug: "bep-sai-gon", district: "Bình Thạnh", rating: 4.4 },
  { id: "hem-ngon", name: "Hẻm Ngon", slug: "hem-ngon", district: "Quận 3", rating: 4.5 },
];

export const fallbackDishes: Dish[] = [
  {
    id: "pho-bo",
    name: "Phở bò",
    slug: "pho-bo",
    description: "Nước dùng thơm, thịt bò mềm, hợp khi muốn một món chắc bụng nhưng không quá nặng.",
    imageUrl: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=1200&q=80",
    rating: 4.8,
    priceMin: 45000,
    priceMax: 75000,
    category: fallbackCategories[0],
    restaurant: fallbackRestaurants[0],
  },
  {
    id: "com-tam-suon",
    name: "Cơm tấm sườn",
    slug: "com-tam-suon",
    description: "Sườn nướng thơm, bì chả và nước mắm chua ngọt. Một lựa chọn kinh điển khi đói thật sự.",
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
    rating: 4.7,
    priceMin: 40000,
    priceMax: 70000,
    category: fallbackCategories[1],
    restaurant: fallbackRestaurants[1],
  },
  {
    id: "bun-cha",
    name: "Bún chả",
    slug: "bun-cha",
    description: "Thịt nướng, bún tươi và rau sống. Hợp những hôm muốn món Việt nhiều hương vị.",
    imageUrl: "https://images.unsplash.com/photo-1569562211093-4ed0d0758f12?auto=format&fit=crop&w=1200&q=80",
    rating: 4.6,
    priceMin: 45000,
    priceMax: 80000,
    category: fallbackCategories[0],
    restaurant: fallbackRestaurants[2],
  },
  {
    id: "banh-mi",
    name: "Bánh mì thịt",
    slug: "banh-mi",
    description: "Nhanh, gọn, giòn nóng. Cứu cánh cho bữa sáng hoặc những ngày lịch dày.",
    imageUrl: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&w=1200&q=80",
    rating: 4.5,
    priceMin: 20000,
    priceMax: 40000,
    category: fallbackCategories[2],
    restaurant: fallbackRestaurants[0],
  },
  {
    id: "lau-thai",
    name: "Lẩu Thái",
    slug: "lau-thai",
    description: "Chua cay, nhiều topping, hợp buổi tối đi cùng bạn bè hoặc gia đình.",
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80",
    rating: 4.7,
    priceMin: 120000,
    priceMax: 250000,
    category: fallbackCategories[3],
    restaurant: fallbackRestaurants[2],
  },
  {
    id: "salad-ga",
    name: "Salad gà áp chảo",
    slug: "salad-ga",
    description: "Nhẹ bụng, giàu đạm, hợp ngày muốn ăn sạch nhưng vẫn đủ năng lượng.",
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80",
    rating: 4.3,
    priceMin: 55000,
    priceMax: 95000,
    category: fallbackCategories[4],
    restaurant: fallbackRestaurants[1],
  },
];
